#!/bin/bash
#
# The MIT License
#
# Copyright (c) 2019 Volodymyr Gorlov (https://github.com/vgorloff)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

set -e

SaNdkPath="/usr/local/ndk/21.3.6528147"
SaCurrentScriptName="$(basename ${BASH_SOURCE[0]})"
SaCurrentScriptDirPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [[ $SHELL =~ "zsh" ]]; then
	SaCurrentScriptDirPath=$(dirname $0:A)
fi

SaToolchainPath=$(cd "$(dirname "$SaCurrentScriptDirPath")/../"; pwd)
if [ ! -f "$SaCurrentScriptDirPath/swift" ]; then
  echo "-> Development mode!"
  SaToolchainPath="$(cd "$(dirname "$SaCurrentScriptDirPath")"; pwd)/ToolChain/swift-android-toolchain"
fi

function usage {
  echo ""
  echo "Usage:"
  echo "   $SaCurrentScriptName -target <target> [-v] [OPTIONS]"
  echo ""
  echo "   Where:"
  echo ""
  echo "   <target> Is one of the following:"
  echo ""
  echo "     - armv7-none-linux-androideabi"
  echo "     - aarch64-unknown-linux-android"
  echo "     - i686-unknown-linux-android"
  echo "     - x86_64-unknown-linux-android"
  echo ""
  echo "   -v Verbose mode."
  echo ""
  echo "   [OPTIONS] Other options for Swift compiler."
  echo ""
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -target)
    SaArchTarget="$2"
    POSITIONAL+=("$1") # save it in an array for later
    POSITIONAL+=("$2") # save it in an array for later
    shift # past argument
    shift # past value
    ;;
    -v)
    SaVerbose=YES
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "$SaArchTarget" ]; then
  echo "The \"-target\" argument is not provided."
  usage
  exit 1
fi

if [ "$SaArchTarget" = "armv7-none-linux-androideabi" ] || [ "$SaArchTarget" = "aarch64-unknown-linux-android" ] || [ "$SaArchTarget" = "i686-unknown-linux-android" ] || [ "$SaArchTarget" = "x86_64-unknown-linux-android" ]; then
  true
else
  echo "Unknown target \"$SaArchTarget\""
  usage
  exit 1
fi

case $SaArchTarget in
  armv7-none-linux-androideabi)
  SaSwiftArch=armv7
  SaCppArch=armeabi-v7a
  SaNdkArch="arm-linux-androideabi"
  SaNdkPlatformArch="arm"
  ;;
  aarch64-unknown-linux-android)
  SaSwiftArch=aarch64
  SaCppArch=arm64-v8a
  SaNdkArch="aarch64-linux-android"
  SaNdkPlatformArch="arm64"
  ;;
  i686-unknown-linux-android)
  SaSwiftArch=i686
  SaCppArch=x86
  SaNdkArch="i686-linux-android"
  SaNdkPlatformArch="x86"
  ;;
  x86_64-unknown-linux-android)
  SaSwiftArch=x86_64
  SaCppArch=x86_64
  SaNdkArch="x86_64-linux-android"
  SaNdkPlatformArch="x86_64"
  ;;
esac

SaNdkToolChain="${SaNdkPath}/toolchains/llvm/prebuilt/darwin-x86_64"
SaNdkGccVersion="4.9"
SaNdkApiVersion="24"
SaSwiftCPath="$SaToolchainPath/usr/bin/swiftc"
SaCmdArgs="-swift-version 5 -tools-directory $SaNdkToolChain"

# See:
# - https://github.com/apple/swift/pull/26366/files
# - https://github.com/apple/swift/pull/25990#issuecomment-522344255
SaCmdArgs="$SaCmdArgs -Xclang-linker --sysroot=${SaNdkPath}/platforms/android-${SaNdkApiVersion}/arch-${SaNdkPlatformArch}"
SaCmdArgs="$SaCmdArgs -Xclang-linker --gcc-toolchain=$SaNdkToolChain"

SaCmdArgs="$SaCmdArgs -Xcc -I${SaNdkPath}/sysroot/usr/include"
SaCmdArgs="$SaCmdArgs -Xcc -I${SaNdkPath}/sysroot/usr/include/${SaNdkArch}"
SaCmdArgs="$SaCmdArgs -L ${SaNdkPath}/sources/cxx-stl/llvm-libc++/libs/${SaCppArch}"
SaCmdArgs="$SaCmdArgs -L ${SaNdkToolChain}/lib/gcc/${SaNdkArch}/${SaNdkGccVersion}.x" # Link the Android NDK's -lstdc++ and libgcc.
SaCmdArgs="$SaCmdArgs -L ${SaNdkToolChain}/sysroot/usr/lib/${SaNdkArch}/${SaNdkApiVersion}" # Link the Android NDK's -lc++
SaCmdArgs="$SaCmdArgs -L ${SaToolchainPath}/usr/lib/swift/android/${SaSwiftArch}"

if [ "$SaVerbose" = "YES" ]; then
  echo "$SaSwiftCPath" $SaCmdArgs "$@"
fi

"$SaSwiftCPath" $SaCmdArgs "$@"
