#!/usr/bin/env ruby
#
# The MIT License
#
# Copyright (c) 2019 Volodymyr Gorlov (https://github.com/vgorloff)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

toolchainDir = File.dirname(File.dirname(__FILE__))

arch = ENV['SA_TOOLCHAIN_SWIFT_ARCH_PATH_COMPONENT']
cppArch = ENV['SA_TOOLCHAIN_NDK_CPP_ARCH_PATH_COMPONENT']
destination = ARGV.first
if destination.nil?
  puts "! Destination directory to copy \"#{arch}\" libraries is not provided."
  exit(1)
end

puts "Copying \"#{arch}\" libraries to \"#{destination}\""
system "mkdir -p \"#{destination}\""

puts toolchainDir

files = Dir["#{toolchainDir}/lib/swift/android/#{arch}" + "/*.so"]
files << "#{toolchainDir}/ndk/sources/cxx-stl/llvm-libc++/libs/#{cppArch}/libc++_shared.so"
files.each { |lib|
   puts "- Copying \"#{lib}\""
   system "cp -f #{lib} #{destination}"
}
