#!/bin/bash
export SA_TOOLCHAIN_SWIFT_ARCH_PATH_COMPONENT=x86_64
export SA_TOOLCHAIN_NDK_ARCH_PATH_COMPONENT=x86_64-linux-android
export SA_TOOLCHAIN_NDK_CPP_ARCH_PATH_COMPONENT=x86_64
export SA_TOOLCHAIN_NDK_PLATFORM_ARCH_PATH_COMPONENT=x86_64
`dirname $0`/swiftc-any-linux-android -target x86_64-unknown-linux-android "$@"