#!/bin/bash
export SA_TOOLCHAIN_SWIFT_ARCH_PATH_COMPONENT=i686
export SA_TOOLCHAIN_NDK_ARCH_PATH_COMPONENT=i686-linux-android
export SA_TOOLCHAIN_NDK_CPP_ARCH_PATH_COMPONENT=x86
export SA_TOOLCHAIN_NDK_PLATFORM_ARCH_PATH_COMPONENT=x86
`dirname $0`/swiftc-any-linux-android -target i686-unknown-linux-android "$@"