#!/usr/bin/env ruby
#
# The MIT License
#
# Copyright (c) 2019 Volodymyr Gorlov (https://github.com/vgorloff)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

ndkPlatformArch = ENV['SA_TOOLCHAIN_NDK_PLATFORM_ARCH_PATH_COMPONENT']
ndkArch = ENV['SA_TOOLCHAIN_NDK_ARCH_PATH_COMPONENT']
swiftArch = ENV['SA_TOOLCHAIN_SWIFT_ARCH_PATH_COMPONENT']
cppArch = ENV['SA_TOOLCHAIN_NDK_CPP_ARCH_PATH_COMPONENT']

toolchainDir = File.dirname(File.dirname(__FILE__))
ndkPath = "#{toolchainDir}/ndk"
ndkGccVersion = "4.9"
ndkApiVersion = "24"
ndkToolChain = "#{ndkPath}/toolchains/llvm/prebuilt/darwin-x86_64"

args = []
# args << "-v"
args << "-tools-directory #{ndkToolChain}"
args << "-sdk #{toolchainDir}/ndk/platforms/android-#{ndkApiVersion}/arch-#{ndkPlatformArch}"
args << "-Xcc -DDEPLOYMENT_TARGET_ANDROID -Xcc -DDEPLOYMENT_TARGET_LINUX -Xcc -DDEPLOYMENT_RUNTIME_SWIFT"
args << "-Xcc -I#{ndkToolChain}/sysroot/usr/include -Xcc -I#{ndkToolChain}/sysroot/usr/include/#{ndkArch}"
args << "-L #{toolchainDir}/ndk/sources/cxx-stl/llvm-libc++/libs/#{cppArch}"
args << "-L #{ndkToolChain}/lib/gcc/#{ndkArch}/#{ndkGccVersion}.x" # Link the Android NDK's libc++ and libgcc.
args << "-L #{toolchainDir}/lib/swift/android/#{swiftArch}"

cmd = "#{toolchainDir}/bin/swiftc " + args.join(" ") + " " + ARGV.join(" ")
puts cmd
system cmd
exit($?.exitstatus)
